// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Css() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<script>\n        tailwind.config = {\n            darkMode: 'class',\n            theme: {\n                extend: {\n                    fontFamily: {\n                        sans: ['Nunito', 'ui-sans-serif', 'system-ui', 'sans-serif'],\n                    },\n                    colors: {\n                        alpine: {\n                            50:  '#f0f7f0',\n                            100: '#d9edd9',\n                            200: '#b3dab4',\n                            300: '#7fc080',\n                            400: '#4fa350',\n                            500: '#2e8330',\n                            600: '#1f6821',\n                            700: '#1a551c',\n                            800: '#164319',\n                            900: '#123816',\n                            950: '#091f0a',\n                        },\n                        stone: {\n                            50:  '#fafaf9',\n                            100: '#f5f5f4',\n                            200: '#e7e5e4',\n                            300: '#d6d3d1',\n                            400: '#a8a29e',\n                            500: '#78716c',\n                            600: '#57534e',\n                            700: '#44403c',\n                            800: '#292524',\n                            900: '#1c1917',\n                            950: '#0c0a09',\n                        },\n                        amber: {\n                            400: '#fbbf24',\n                            500: '#f59e0b',\n                            600: '#d97706',\n                        },\n                        summit: {\n                            DEFAULT: '#4a7c6f',\n                            light: '#6aab9c',\n                            dark: '#2d5a4f',\n                        },\n                    },\n                },\n            },\n        }\n    </script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
