name: Build and Test Where Am I

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout github action"
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Set up gotestfmt
        uses: gotesttools/gotestfmt-action@v2

      - name: Run Build
        run: go build main.go
